use laravels `loadMigrationsFrom()` method
eveseat/api pull request #27
Opened 2018-11-26 16:12 UTC by herpaderpaldent

instead of publishing assets

Referring to the documentation https://laravel.com/docs/5.5/packages#migrations

2018-11-26 18:17 UTC, warlof requested changes

2018-11-26 18:17 UTC, warlof commented on src/ApiServiceProvider.php
> +    public function add_migrations()
Should be private instead public as it will (and probably should) never be call outside of the provider.

2018-11-26 19:53 UTC, warlof approved these changes

2018-12-01 07:30 UTC, leonjza approved these changes

2018-12-06 21:37 UTC, merged